/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author jcalahuche
 */
public class V_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form V_Calculadora
     */
    public V_Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Screen = new javax.swing.JTextField();
        Calculate = new javax.swing.JButton();
        Number1 = new javax.swing.JButton();
        Number2 = new javax.swing.JButton();
        Number3 = new javax.swing.JButton();
        Number4 = new javax.swing.JButton();
        Number5 = new javax.swing.JButton();
        Number6 = new javax.swing.JButton();
        Number7 = new javax.swing.JButton();
        Number8 = new javax.swing.JButton();
        Number9 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Subtract = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Number0 = new javax.swing.JButton();
        Clean = new javax.swing.JButton();
        Dot = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        startParenthesis = new javax.swing.JButton();
        endParenthesis = new javax.swing.JButton();
        Power = new javax.swing.JButton();
        Remainder = new javax.swing.JButton();
        Root = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 25, 25));
        setResizable(false);

        Screen.setBackground(new java.awt.Color(51, 51, 51));
        Screen.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Screen.setForeground(new java.awt.Color(255, 255, 255));
        Screen.setActionCommand("<Not Set>");
        Screen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Screen.setMargin(new java.awt.Insets(6, 6, 6, 6));
        Screen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenActionPerformed(evt);
            }
        });
        Screen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ScreenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ScreenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ScreenKeyTyped(evt);
            }
        });

        Calculate.setBackground(new java.awt.Color(78, 114, 79));
        Calculate.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Calculate.setForeground(new java.awt.Color(255, 255, 255));
        Calculate.setText("=");
        Calculate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Calculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calculate.setMinimumSize(new java.awt.Dimension(163, 50));
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        Number1.setBackground(new java.awt.Color(25, 25, 25));
        Number1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number1.setForeground(new java.awt.Color(255, 255, 255));
        Number1.setText("1");
        Number1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number1.setMinimumSize(new java.awt.Dimension(50, 50));
        Number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number1ActionPerformed(evt);
            }
        });

        Number2.setBackground(new java.awt.Color(25, 25, 25));
        Number2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number2.setForeground(new java.awt.Color(255, 255, 255));
        Number2.setText("2");
        Number2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number2.setMinimumSize(new java.awt.Dimension(50, 50));
        Number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number2ActionPerformed(evt);
            }
        });

        Number3.setBackground(new java.awt.Color(25, 25, 25));
        Number3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number3.setForeground(new java.awt.Color(255, 255, 255));
        Number3.setText("3");
        Number3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number3.setMinimumSize(new java.awt.Dimension(50, 50));
        Number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number3ActionPerformed(evt);
            }
        });

        Number4.setBackground(new java.awt.Color(25, 25, 25));
        Number4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number4.setForeground(new java.awt.Color(255, 255, 255));
        Number4.setText("4");
        Number4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number4.setMinimumSize(new java.awt.Dimension(50, 50));
        Number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number4ActionPerformed(evt);
            }
        });

        Number5.setBackground(new java.awt.Color(25, 25, 25));
        Number5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number5.setForeground(new java.awt.Color(255, 255, 255));
        Number5.setText("5");
        Number5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number5.setMinimumSize(new java.awt.Dimension(50, 50));
        Number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number5ActionPerformed(evt);
            }
        });

        Number6.setBackground(new java.awt.Color(25, 25, 25));
        Number6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number6.setForeground(new java.awt.Color(255, 255, 255));
        Number6.setText("6");
        Number6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number6.setMinimumSize(new java.awt.Dimension(50, 50));
        Number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number6ActionPerformed(evt);
            }
        });

        Number7.setBackground(new java.awt.Color(25, 25, 25));
        Number7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number7.setForeground(new java.awt.Color(255, 255, 255));
        Number7.setText("7");
        Number7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number7.setMinimumSize(new java.awt.Dimension(50, 50));
        Number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number7ActionPerformed(evt);
            }
        });

        Number8.setBackground(new java.awt.Color(25, 25, 25));
        Number8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number8.setForeground(new java.awt.Color(255, 255, 255));
        Number8.setText("8");
        Number8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number8.setMinimumSize(new java.awt.Dimension(50, 50));
        Number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number8ActionPerformed(evt);
            }
        });

        Number9.setBackground(new java.awt.Color(25, 25, 25));
        Number9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number9.setForeground(new java.awt.Color(255, 255, 255));
        Number9.setText("9");
        Number9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number9.setMinimumSize(new java.awt.Dimension(50, 50));
        Number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number9ActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(61, 62, 89));
        Add.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("+");
        Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.setMinimumSize(new java.awt.Dimension(50, 50));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Subtract.setBackground(new java.awt.Color(61, 62, 89));
        Subtract.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Subtract.setForeground(new java.awt.Color(255, 255, 255));
        Subtract.setText("-");
        Subtract.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Subtract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Subtract.setMinimumSize(new java.awt.Dimension(50, 50));
        Subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractActionPerformed(evt);
            }
        });

        Multiply.setBackground(new java.awt.Color(61, 62, 89));
        Multiply.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Multiply.setForeground(new java.awt.Color(255, 255, 255));
        Multiply.setText("×");
        Multiply.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Multiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Multiply.setMinimumSize(new java.awt.Dimension(50, 50));
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });

        Divide.setBackground(new java.awt.Color(61, 62, 89));
        Divide.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Divide.setForeground(new java.awt.Color(255, 255, 255));
        Divide.setText("÷");
        Divide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Divide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Divide.setMinimumSize(new java.awt.Dimension(50, 50));
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });

        Number0.setBackground(new java.awt.Color(25, 25, 25));
        Number0.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Number0.setForeground(new java.awt.Color(255, 255, 255));
        Number0.setText("0");
        Number0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Number0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Number0.setMinimumSize(new java.awt.Dimension(50, 50));
        Number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Number0ActionPerformed(evt);
            }
        });

        Clean.setBackground(new java.awt.Color(204, 153, 0));
        Clean.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Clean.setForeground(new java.awt.Color(255, 255, 255));
        Clean.setText("C");
        Clean.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clean.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clean.setMinimumSize(new java.awt.Dimension(50, 50));
        Clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CleanActionPerformed(evt);
            }
        });

        Dot.setBackground(new java.awt.Color(61, 62, 89));
        Dot.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Dot.setForeground(new java.awt.Color(255, 255, 255));
        Dot.setText(".");
        Dot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dot.setMinimumSize(new java.awt.Dimension(50, 50));
        Dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(204, 153, 0));
        Back.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("←");
        Back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.setMinimumSize(new java.awt.Dimension(50, 50));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        startParenthesis.setBackground(new java.awt.Color(61, 62, 89));
        startParenthesis.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        startParenthesis.setForeground(new java.awt.Color(255, 255, 255));
        startParenthesis.setText("(");
        startParenthesis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startParenthesis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startParenthesis.setMinimumSize(new java.awt.Dimension(50, 50));
        startParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startParenthesisActionPerformed(evt);
            }
        });

        endParenthesis.setBackground(new java.awt.Color(61, 62, 89));
        endParenthesis.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        endParenthesis.setForeground(new java.awt.Color(255, 255, 255));
        endParenthesis.setText(")");
        endParenthesis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        endParenthesis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        endParenthesis.setMinimumSize(new java.awt.Dimension(50, 50));
        endParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endParenthesisActionPerformed(evt);
            }
        });

        Power.setBackground(new java.awt.Color(61, 62, 89));
        Power.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Power.setForeground(new java.awt.Color(255, 255, 255));
        Power.setText("^");
        Power.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Power.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Power.setMinimumSize(new java.awt.Dimension(50, 50));
        Power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerActionPerformed(evt);
            }
        });

        Remainder.setBackground(new java.awt.Color(61, 62, 89));
        Remainder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Remainder.setForeground(new java.awt.Color(255, 255, 255));
        Remainder.setText("%");
        Remainder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Remainder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Remainder.setMinimumSize(new java.awt.Dimension(50, 50));
        Remainder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemainderActionPerformed(evt);
            }
        });

        Root.setBackground(new java.awt.Color(61, 62, 89));
        Root.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Root.setForeground(new java.awt.Color(255, 255, 255));
        Root.setText("√");
        Root.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Root.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Root.setMinimumSize(new java.awt.Dimension(50, 50));
        Root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Screen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Power, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Remainder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Number1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Number4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Subtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Number7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Number9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(startParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endParenthesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Number0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Root, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Power, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Remainder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startParenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculateActionPerformed

    private void Number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number1ActionPerformed

    private void Number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number2ActionPerformed

    private void Number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number3ActionPerformed

    private void Number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number6ActionPerformed

    private void Number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number4ActionPerformed

    private void Number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number5ActionPerformed

    private void Number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number8ActionPerformed

    private void Number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number9ActionPerformed

    private void Number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number7ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void SubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubtractActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultiplyActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DivideActionPerformed

    private void ScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenActionPerformed

    private void Number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Number0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Number0ActionPerformed

    private void CleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CleanActionPerformed

    private void DotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DotActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void ScreenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScreenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenKeyPressed

    private void ScreenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScreenKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenKeyReleased

    private void ScreenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ScreenKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenKeyTyped

    private void startParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startParenthesisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startParenthesisActionPerformed

    private void endParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endParenthesisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endParenthesisActionPerformed

    private void PowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerActionPerformed

    private void RootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RootActionPerformed

    private void RemainderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemainderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemainderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Calculator().setVisible(true);
            }
        });
    }
    
    public JButton[] getButtons() {
        JButton[] buttons = {
            Number0, 
            Number1, 
            Number2, 
            Number3, 
            Number4, 
            Number5, 
            Number6, 
            Number7, 
            Number8, 
            Number9,
            Add,
            Subtract,
            Multiply,
            Divide,
            Remainder,
            Power,
            Root,
            Clean,
            Back,
            startParenthesis,
            endParenthesis,
            Calculate,
            Dot,
        };
        
        return buttons;
    }

    public JButton getCalculate() {
        return Calculate;
    }

    public void setCalculate(JButton Calculate) {
        this.Calculate = Calculate;
    }

    public JButton getDivide() {
        return Divide;
    }

    public void setDivide(JButton Divide) {
        this.Divide = Divide;
    }

    public JButton getClean() {
        return Clean;
    }

    public void setClean(JButton Clean) {
        this.Clean = Clean;
    }

    public JButton getMultiply() {
        return Multiply;
    }

    public void setMultiply(JButton Multiply) {
        this.Multiply = Multiply;
    }

    public JButton getNumber0() {
        return Number0;
    }

    public void setNumber0(JButton Number0) {
        this.Number0 = Number0;
    }

    public JButton getNumber1() {
        return Number1;
    }

    public void setNumber1(JButton Number1) {
        this.Number1 = Number1;
    }

    public JButton getNumber2() {
        return Number2;
    }

    public void setNumber2(JButton Number2) {
        this.Number2 = Number2;
    }

    public JButton getNumber3() {
        return Number3;
    }

    public void setNumber3(JButton Number3) {
        this.Number3 = Number3;
    }

    public JButton getNumber4() {
        return Number4;
    }

    public void setNumber4(JButton Number4) {
        this.Number4 = Number4;
    }

    public JButton getNumber5() {
        return Number5;
    }

    public void setNumber5(JButton Number5) {
        this.Number5 = Number5;
    }

    public JButton getNumber6() {
        return Number6;
    }

    public void setNumber6(JButton Number6) {
        this.Number6 = Number6;
    }

    public JButton getNumber7() {
        return Number7;
    }

    public void setNumber7(JButton Number7) {
        this.Number7 = Number7;
    }

    public JButton getNumber8() {
        return Number8;
    }

    public void setNumber8(JButton Number8) {
        this.Number8 = Number8;
    }

    public JButton getNumber9() {
        return Number9;
    }

    public void setNumber9(JButton Number9) {
        this.Number9 = Number9;
    }

    public void setNumbers(JButton Number9) {
        this.Number9 = Number9;
    }

    public JTextField getScreen() {
        return Screen;
    }

    public void setScreen(JTextField Screen) {
        this.Screen = Screen;
    }

    public JButton getSubtract() {
        return Subtract;
    }

    public void setSubtract(JButton Subtract) {
        this.Subtract = Subtract;
    }
    
    public JButton getAdd() {
        return Add;
    }

    public void setAdd(JButton Add) {
        this.Add = Add;
    }

    public JButton getDot() {
        return Dot;
    }

    public void setDot(JButton Dot) {
        this.Dot = Dot;
    }

    public JButton getBack() {
        return Back;
    }

    public void setBack(JButton Back) {
        this.Back = Back;
    }

    public JButton getEndParenthesis() {
        return endParenthesis;
    }

    public void setEndParenthesis(JButton endParenthesis) {
        this.endParenthesis = endParenthesis;
    }

    public JButton getPower() {
        return Power;
    }

    public void setPower(JButton potencia) {
        this.Power = potencia;
    }

    public JButton getStartParenthesis() {
        return startParenthesis;
    }

    public void setStartParenthesis(JButton startParenthesis) {
        this.startParenthesis = startParenthesis;
    }

    public JButton getRemainder() {
        return Remainder;
    }

    public void setRemainder(JButton Remainder) {
        this.Remainder = Remainder;
    }

    public JButton getRoot() {
        return Root;
    }

    public void setRoot(JButton Root) {
        this.Root = Root;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JButton Calculate;
    private javax.swing.JButton Clean;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Dot;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Number0;
    private javax.swing.JButton Number1;
    private javax.swing.JButton Number2;
    private javax.swing.JButton Number3;
    private javax.swing.JButton Number4;
    private javax.swing.JButton Number5;
    private javax.swing.JButton Number6;
    private javax.swing.JButton Number7;
    private javax.swing.JButton Number8;
    private javax.swing.JButton Number9;
    private javax.swing.JButton Power;
    private javax.swing.JButton Remainder;
    private javax.swing.JButton Root;
    private javax.swing.JTextField Screen;
    private javax.swing.JButton Subtract;
    private javax.swing.JButton endParenthesis;
    private javax.swing.JButton startParenthesis;
    // End of variables declaration//GEN-END:variables
}
